### ISSUE TITLE
Mekanism/Applied Enginetics 2 Breaking issues.

### ISSUE THREAD

**Issue by GybelsBavo** [pchard/JWR#25]
Since the start of the game i had some issues with mekanism: I could break a machine/cable but it disapeared like creative mod, i tried all wrenches they are ingame but none worked.

After that i started working on an me system, i noticed when i placed an me cable wrong it would disapear like mekanism cables, then i placed an crafting terminal (was in the wrong spot broke it too also gone)

Further i had no isseus  but i didn't try any other mods like Reactors etc..
 -Gybelsbavo

Ingame: Gybelsbavo

**Comment by GybelsBavo** [comment]
Also, if i look at a mekanism machine it all says Enrichment chamber.

And there are 2 block info hotbars at the top how do i remove 1?

**Comment by GybelsBavo** [comment]
I lost 1 Energy cube (mekanism) 3 basic universal cables,4me cables,1me crafting terminal
a heat generator and a mettalergic infuser.

**Comment by GybelsBavo** [comment]
,personal chest (mekanism)

**Comment by wolfiepawz** [comment]
Can't reproduce the issue.
Digital Miner can disappear when it's somehow turned into a bounding block, but this has been an issue since 1.7.10
