### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by SailoX** [pchard/JWR#28]
left to go take a shower at full hp and nothing spawned around me in my home. Logged back on after switching internet connections because of problems with my internet and was down to half a heart, a hoard of zombies spawned in my home where I logged out, and my tinkers hammer broken.

EDIT 1; server reset and I logged back in to a pumpkin head zombie spawned right on top of me in the same place my character was.

**Comment by wolfiepawz** [comment]
The solution to the hoard of zombies are simple. Bloodmoon is on the server.

I'll investigate the rest of your issues.

**Comment by SailoX** [comment]
they can spawn in your fully lit home on bloodmoon? dont know much about bloodmoon.

**Comment by wolfiepawz** [comment]
No they shouldn't. But check if your place is fully lit.. And not just a bit.

**Comment by SailoX** [comment]
I did, the lowest light lvl is 8

**Comment by SailoX** [comment]
I relogged because of an HP issue, tinkers hammer broke again.

**Comment by SailoX** [comment]
got some new info. After changing my morph and switching to my hammer, my hammer broke from half durability.

**Comment by SailoX** [comment]
it seems to be one particular morph that might be causing this. I will do more testing to see.

**Comment by SailoX** [comment]
The shaman morph might be the culprit

**Comment by wolfiepawz** [comment]
Just remember, the modpack IS in beta, so bugs will be there.. I'll do some investigating when I have time today.

**Comment by SailoX** [comment]
np man, I know. so no worries here :3
