### ISSUE TITLE
Strange behaviour of the login-TP (JWR)

### ISSUE THREAD

**Issue by IceSkythe** [pchard/JWR#3]
The last 4 or 5 times i looged in I noticed something strange

If I was flying while logging out (or having a dc) and logg in, It wouldn't TP me to spawn,instead I get a message with "Pending teleportation request cancelled."
It seems,it is caused by the fact,that the flying-effect is removed the moment i logg in and i fall to the ground( don't know how to describe it better).
Tested it multiple times,it only appears,when i was flying,if I'm on the ground when logging out,it behaves normal... <.<

I'm in batmorph and have the flying-gene, not sure,whats causing it

**Comment by wolfiepawz** [comment]
This is perfectly normal since we have implemented some neat plugin features and will be overhauling the TPSpawn plugin soon to fix this issue.
