### ISSUE TITLE
Single player crash on opening Craft

### ISSUE THREAD

**Issue by Phoenyx33** [pchard/JWR#5]
My apologies for putting this on discord/general and support at first. I don't know why this is happening as I've given JWR 4Gig of memory, but every time after the first that I open the crafting table, it kicks me to the front page of the mod... where I chose single- or multi-player. Do you have a clue why it's doing this? Crash log is attached.
[crash-2016-08-25_15.53.17-server.txt](https://github.com/pchard/JWR/files/438466/crash-2016-08-25_15.53.17-server.txt)

**Comment by wolfiepawz** [comment]
It looks like it could be Gany's Surface's crafting Table that does this.

Have you tried converting your normal crafting table into a tinkers crafting table?

**Comment by Phoenyx33** [comment]
I would but I have to use the normal table to create the parts for the Tinker's table and I haven't been able to get that far. It normally crashes the second or third time I try to use the normal table.

Sent from my Sprint Samsung Galaxy S® 6.

-------- Original message --------

**Comment by wolfiepawz** [comment]
No no.. You simple put the vanilla crafting table and put in the crafting grid in your inventory and you'll have a Tinker's Crafting Table :)
