### ISSUE TITLE
Unable to start the modpack

### ISSUE THREAD

**Issue by Spotter5** [pchard/JWR#6]
Hi, I am unable to start the modpack, and i'm not entirly sure why.. I am including a copy of the log it spits out. Basically I press play in ATlauncher, that closes its window as normal, stuff happens in the log then ATlauncher restarts. As far as i'm aware i have set it to 4GB. its just in the ATlauncher settings right?, and Java is up to date as it made me do an update to it the other week or so.
  ##[mclog.txt](https://github.com/pchard/JWR/files/443457/mclog.txt)

**Comment by wolfiepawz** [comment]
Have you added any mods except Optifine?

**Comment by Spotter5** [comment]
yeah, forgot I added them, I have

Industrialcraft
advanced solar panel
advanced machines
immibis core
railcraft
not enough resources
random things
decocraft
and  of course, optifine

I'll see if any have updates to them

**Comment by wolfiepawz** [comment]
That's why it won't work. These mods have been tested on this modpack in the past and is not compatible.

**Comment by Spotter5** [comment]
Thats strange, i noticed  i had two version of industrialcraft, one i added one already in the mod, removed one and its working fine! thanks though :)
