### ISSUE TITLE
F&A Dinosaurs are broken or something :s

### ISSUE THREAD

**Issue by WintersMercy** [pchard/JWR#8]
So I found this bug whenever I log off and another friend is still on the dino will continue to grow but at some moment the dinosaur will not beable to be moved from it's spot.
I tested breaking the blocks below it : Just falls down and still won't move
I have tried pushing it with water : Just flowed back into place after about being pushed 3 blocks 
Made sure it was fed and happy with it on follow/Wander : Doesn't seem to play out with anything
I have tested these on 3 animals on the mod pack
Trike : Alive : Bugged in place
Smildon : Alive : Bugged in place
Allosaurus : Deceased: Deid during testing, it was low hp from not eating out of the feeder even though it was tamed and next to it and a skele shot it resulting in it's death
So I still haven't figured out what is causing it but whatever it is it's annoying :( 
- WintersMercy

**Comment by wolfiepawz** [comment]
Unfortunately, there's not much we can do about this, since it's the mod that's acting this way, not the server nor modpack.
